name: "create-version-tag"
description: "Creates a tag on the specified version"
branding:
  icon: "bookmark"
  color: "green"
inputs:
  pact_broker:
    description: "The url of your pact broker"
    required: true
  pact_broker_token:
    description: "Your pact broker token"
    required: true
  application_name:
    description: "The name of your application (usually project name)"
    required: true
  version:
    description: "Version to tag"
    required: true
  tag:
    description: "Tag to create"
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/createTag.sh
      shell: bash
